//<auto-generated/>
namespace Manager.Manager
{
    using global::Manager.IManager;
    using Model.NoteModel;
    using Repository.IRepository;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    public class NoteManager : INoteManager
    {
        private readonly INoteRepository repository;
        public NoteManager(INoteRepository note)
        {
            note = repository;
        }
        public NoteManager()
        {

        }
        public async Task AddNotes(NoteModel note)
        {
            await this.repository.AddNotes(note);
        }

        public async Task DeleteNote(int id)
        {
            await this.repository.DeleteNote(id);
        }

        public List<NoteModel> GetNote(int id)
        {
            var result = this.repository.GetNote(id);
            return result;
        }

        public List<NoteModel> GetAllNotes()
        {
            return this.repository.GetAllNotes();
        }

        public Task UpdateNote(NoteModel note)
        {
            return this.repository.UpdateNote(note);
        }
    }
}